django_spotify/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
	url(r'^$', RedirectView.as_view(url='/spotify_list', permanent=True), name='index'),
	url(r'^spotify_list/', include('spotify_list.urls')),
    url(r'^admin/', admin.site.urls),
]

spotify_list/urls.py
from django.conf.urls import url
from . import views

app_name = 'spotify_list'
urlpatterns = [
    url(r'^$', views.SongListView.as_view(), name='index'),
    url(r'^(?P<country>[a-z]*)$', views.SongListView.as_view(), name = 'index'),
    url(r'^download_file/(?P<yt_id>[-\w]+)', views.download_file, name = 'download_file'),
    url(r'^update_lists$', views.download_and_parse_csvs, name='dl_and_parse'),
    url(r'^borrar_mp3_y_csv$', views.borrar_mp3_y_csv, name='borrar_mp3_y_csv'),
    url(r'^dl_any_mp3$', views.dl_any_mp3, name='dl_any_mp3'),
]

spotify_list/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Song (models.Model):
	title = models.CharField(max_length=140)
	artist = models.CharField(max_length=140)
	position = models.IntegerField()
	yt_id = models.CharField(max_length=20)
	spotify_id = models.CharField(max_length=40)

	def __unicode__(self):
		return "{0}. By: {1}".format(self.title, self.artist)

class Playlist (models.Model):
	title = models.CharField(max_length=100)
	songs = models.ForeignKey(Song)

class Genre (models.Model):
	title = models.CharField(max_length=30)
	playlists = models.ForeignKey(Playlist)

spotify_list/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from django import template
from django.views.generic import ListView, DetailView

import os
import csv
import wget
import logging
import unicodedata
import json
import youtube_dl

from apiclient.discovery import build
from apiclient.errors import HttpError
from oauth2client.tools import argparser

from spotify_list.models import Song, Playlist



# Set DEVELOPER_KEY to the API key value from the APIs & auth > Registered apps
# tab of
#   https://cloud.google.com/console
# Please ensure that you have enabled the YouTube Data API for your project.
DEVELOPER_KEY = "AIzaSyBIHbo9jl62SMsy4Eos7qhgidSEHHChUI0"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"


def youtube_search(search_string, max_results):
    youtube = build(YOUTUBE_API_SERVICE_NAME,
                    YOUTUBE_API_VERSION,
                    developerKey=DEVELOPER_KEY)

    # Call the search.list method to retrieve results matching the specified
    # query term.
    search_response = youtube.search().list(
                                    q=search_string,
                                    part="id,snippet",
                                    maxResults=max_results
                                    ).execute()

    videos = []
    channels = []
    playlists = []

    # Add each result to the appropriate list, and then display the lists of
    # matching videos, channels, and playlists.
    search_result = None
    for search_result in search_response.get("items", []):
        if search_result["id"]["kind"] == "youtube#video":
            videos.append("%s (%s)" % (search_result["snippet"]["title"],
                                        search_result["id"]["videoId"]))

    if search_result is not None and 'videoId' in search_result['id']:
        return (search_result['id']['videoId'])
    else:
        return("")


def country_code_to_search_term(country_code):
        if country_code == "do":
            pl_search_term = 'Top 100 do'
        elif country_code == "spain":
            pl_search_term = 'Top 100 es'
        elif country_code == "usa":
            pl_search_term = 'Top 100 us'
        elif country_code == "uk":
            pl_search_term = 'Top 100 gb'
        elif country_code == "global":
            pl_search_term = 'Top 100 global'
        else:
            pl_search_term = 'Top 100 global' 
        return pl_search_term


def download_file(request, yt_id):

    def remove_accents(mystr):
        """Changes accented characters (áüç...) to their unaccented counterparts (auc...)."""
        s = ''.join((c for c in unicodedata.normalize('NFD',unicode(mystr)) if unicodedata.category(c) != 'Mn'))
        return s.decode()

    def hooks(data):
        if data['status'] == 'finished':
            global filename
            data['filename'] = remove_accents(data['filename']).replace(",", "")
            filename = data['filename']
            filename = os.path.splitext(filename)[0]+'.mp3'
            return filename

    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'progress_hooks': [hooks],
        'outtmpl': '%(title)s.%(ext)s'
    }

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download(['http://www.youtube.com/watch?v='+yt_id])

    try:
        response = HttpResponse()
        response['Content-Type'] = 'application/mp3'
        response['X-Accel-Redirect'] = '/files/' + filename
        response['Content-Disposition'] = 'attachment;filename=' + filename
    except Exception:
        raise Http404
    return response


def dl_any_mp3(request):
    context = {}
    return render(request, 'spotify_list/dl_any_mp3.html', context)


def download_and_parse_csvs(request):

    countries = ['global', 'es', 'us', 'do', 'gb']

    song_fields = ['position', 'title', 'artist', 'streams', 'spotify_id', 'yt_id']

    Playlist.objects.all().delete()
    Song.objects.all().delete()

    for country in countries:

        url = 'https://spotifycharts.com/regional/'+country+'/daily/latest/download'

        pl_title = "Top 100 " + country
        pl_spotify_id = "NA"

        csvfile = wget.download(url)

        # Parse the CSV file
        songs = []
        with open(csvfile, 'rb') as csvfile:
            reader = csv.reader(csvfile, delimiter=str(u','), quotechar=str(u'"'))
            for row in reader:
                print ("Parseando la row = %s" % row)
                song_dict = {}
                for i, e in enumerate(row):
                    song_dict[song_fields[i]] = e.decode('utf-8')
                    if i == len(row) - 1:
                        # Extraer el spotify_id de la url leida del archivo CSV
                        song_dict[song_fields[i]] = e.decode('utf-8').rsplit('/', 1)[-1]

                if song_dict['position'] == "101":
                    break

                # buscar en Youtube el video correspondiente a cada canción
                try:
                    song_dict[song_fields[len(song_fields)-1]] = youtube_search(song_dict['title']+' '+song_dict['artist'], 1)

                    try:
                        s = Song(position = song_dict['position'],
                                 title = song_dict['title'],
                                 artist = song_dict['artist'],
                                 yt_id = song_dict['yt_id'],
                                 spotify_id = song_dict['spotify_id'])
                        s.save()

                        pl = Playlist(title = pl_title,
                                      songs = s)
                        pl.save()
                    except ValueError, e:
                        print "Pass: %s" % e

                except HttpError, e:
                    print "An HTTP error %d occurred:\n%s" % (e.resp.status, e.content)
                # fin busqueda en youtube

    context = {}
    context['country'] = country
    context['songs'] = songs
    return render(request, 'spotify_list/update_lists.html', context)


def borrar_mp3_y_csv (request):

    filelist = [ f for f in os.listdir(".") if f.endswith(".mp3") or f.endswith(".csv")]
    for f in filelist:
        os.remove(f)
    context = {}
    return render(request, 'spotify_list/borrar_mp3_y_csv.html', context)


class SongListView(ListView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super(SongListView, self).get_context_data(**kwargs)
        context['country'] = self.kwargs.get("country", "global")
        return context

    def get_queryset(self, **kwargs):
        country = self.kwargs.get("country", "global")
        pl_search_term = country_code_to_search_term(country)       
        queryset = Song.objects.filter(playlist__title=pl_search_term).order_by('position').distinct('position')
        return queryset

# class SongDetailView(DetailView):
#     model = Song

#     def get_context_data(self, **kwargs):
#         context = super(SongListView, self).get_context_data(**kwargs)
#         context['country'] = self.kwargs.get("country", "global")
#         print("context['object_list'] = %s" % context["object_list"])
#         return context

spotify_list/templates/index.html
<html>
<head></head>
<body>que pasa tronco</body>
</html>

spotify_list/templates/spotify_list/borrar_mp3_y_csv.html
<html>
<head>
	<title></title>
</head>
<body>
	Files deleted.
</body>
</html>

spotify_list/templates/spotify_list/dl_any_mp3.html
<html>
<head>
	{% load staticfiles %}
  	<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'spotify_list/styles2.css' %}">
</head>
<body>
	<div class="centered-container">
		<div class="dl-title">
			<h1><strong>Descarga cualquier canción</strong></h1>
		</div>
		<div id="yt_link_input_div">
			<input id="yt_link_input" class="buscador" type="text" onchange="parse_id()" placeholder="Introduce aquí link a vídeo de YouTube." style="width:600px"/>
		</div>
		<div style="margin-top: 1.2em;">
			<a href="#" id="yt_dl_link">
				<button class="btn btn-default btn-lg btn-primary">
					Descargar MP3
				</button>
			</a>

			<a href="{% url 'spotify_list:index' %}" id="yt_dl_link">
	      		<button class="btn btn-default btn-lg btn-warning">Volver</button>
	      	</a>

		</div>
	</div>
	<br/>
	<br/>
	<br/>
	<br/>
	<script type="text/javascript">
		function parse_id() {
			var video_id = document.getElementById('yt_link_input').value.split('v=')[1];
			if(typeof video_id === 'undefined') {
				video_id = document.getElementById('yt_link_input').value.split('youtu.be/')[1];
			}
			var ampersandPosition = video_id.indexOf('&');
			if(ampersandPosition != -1) {
			  video_id = video_id.substring(0, ampersandPosition);
			}
			document.getElementById('yt_dl_link').setAttribute('href', "download_file/"+video_id);
		}
	</script>
</body>
</html>

spotify_list/templates/spotify_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Top Spotify Songs to MP3</title>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700|Merriweather:400italic,400,700' rel='stylesheet' type='text/css'>
  <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js"></script>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'spotify_list/styles.css' %}">
  <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script type="text/javascript">
    // Define a new module for our app. The array holds the names of dependencies if any.
    var app = angular.module("instantSearch", []);

    // Create the instant search filter
    app.filter('searchFor', function(){

      // All filters must return a function. The first parameter
      // is the data that is to be filtered, and the second is an
      // argument that may be passed with a colon (searchFor:searchString)

      return function(arr, searchString){

        if(!searchString){
          return arr;
        }

        var result = [];

        searchString = searchString.toLowerCase();

        // Using the forEach helper method to loop through the array
        angular.forEach(arr, function(item){

          if((item.title.toLowerCase().indexOf(searchString) !== -1) || 
              (item.artist.toLowerCase().indexOf(searchString) !== -1) ){
            result.push(item);
          }

        });

        return result;
      };

    });
    // Instant filter search end.
  </script>
</head>

{% load spotify_extras %}

<body id="home">

  <div class="page-wrap">

  <div class="alert alert-success" role="alert">
    <a href="{% url 'spotify_list:dl_any_mp3' %}" class="alert-link">
      Nuevo: Extraer MP3 de cualquier vídeo.
    </a>
  </div>

    <div class="content col-md-offset-2 col-md-8">
      <h1 class="header">Top 100 canciones de <span class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            {{ country }}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="{% url 'spotify_list:index' 'spain' %}">Spain</a></li>
            <li><a href="{% url 'spotify_list:index' 'usa' %}"}}>USA</a></li>
            <li><a href="{% url 'spotify_list:index' 'uk' %}"}}>U.K.</a></li>
            <li><a href="{% url 'spotify_list:index' 'do' %}">R.D.</a></li>
            <li><a href="/spotify_list/global"}}>Mundial</a></li>
          </ul>
        </span>
      </h1>

      <div ng-app="instantSearch" ng-init="items={{songs | json}}">
        <div class="bar buscador">
          <input type="text" size="40" ng-model="searchString" placeholder="¿Buscas alguna canción o artista?" />
        </div>

        <div class="all-songs-container" ng-repeat="i in items | searchFor: searchString">
          <div class="song-container" style="min-height: 160px; width:100%;">
            <div class="primera-fila" style="width:100%; margin-left:10%; font-weight: bold; font-size: 1.5em;">
              <b>{% verbatim %}{{i.title}}{% endverbatim %}</b>
            </div>
            <div class="segunda-fila">
              <div class="posicion" style="width:10%; float:left; font-weight: bold; font-size: 3.5em; color: #707070;">
                <b>{% verbatim %}{{i.position}}{% endverbatim %}</b>
              </div>
              <div class="artista" style="width:90%; color: #707070;">
                <b>{% verbatim %}{{i.artist}}{% endverbatim %}</b>
              </div>
            </div>
            <div class="tercera-fila-fila" style="width:100%; margin-left:10%; padding-top: 10px;">
              <button type="button" class="btn btn-default btn-lg spotify" data-spotify_id="{% verbatim %}{{ i.spotify_id }}{% endverbatim %}">
                <span class="glyphicon glyphicon-music" aria-hidden="true"></span> - Escuchar en Spotify
              </button>


              <button type="button" class="btn btn-default btn-lg yt" data-yt_id= "{% verbatim %}{{ i.yt_id }}{% endverbatim %}">
                <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> - Ver vídeo
              </button>

              <a href="/spotify_list/download_file/{% verbatim %}{{i.yt_id}}{% endverbatim %}">
              <button type="button" class="btn btn-default btn-lg">
                <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span> - Descargar MP3
              </button>
              </a>

              <div class="embedded-spotify" id="{% verbatim %}{{ i.spotify_id }}{% endverbatim %}"></div>
              <div class="embedded-yt" id="{% verbatim %}{{ i.yt_id }}{% endverbatim %}"></div>
            </div>
          </div>
        </div>
        <br/>
      </div>

    </div>
  </div>
  <div class="clearfix"></div>

  <div class="site-footer">
  Site by: <a target="_blank" href="http://ricardomol.com">Ricardo Molina</a>.
  </div>

  <script type="text/javascript">
  $(function(){

      $('.spotify').click(function(e){
        e.preventDefault(); // optional
        $('.embedded-yt').empty();
        $('.embedded-spotify').empty();
        var selected_spotify_id = $(this).attr("data-spotify_id");
        var selected_spotify_div = $("#" + selected_spotify_id);
        selected_spotify_div.html("<iframe src='https://embed.spotify.com/?uri=spotify:track:" + selected_spotify_id + "' width='640' height='80' frameborder='0' allowtransparency='true'></iframe>");
      });
      
      $('.yt').click(function(e){
        e.preventDefault(); // optional
        $('.embedded-yt').empty();
        $('.embedded-spotify').empty();
        var selected_yt_id = $(this).attr("data-yt_id");
        var selected_yt_div = $("#" + selected_yt_id);
        selected_yt_div.html("<iframe width='640' height='390' allowfullscreen src='http://www.youtube.com/embed/" + selected_yt_id + "?&playsinline=1&autoplay=1" + "'></iframe>");
      });

  });


/*  // Define a new module for our app. The array holds the names of dependencies if any.
  var app = angular.module("instantSearch", []);

  // Create the instant search filter
  app.filter('searchFor', function(){

    // All filters must return a function. The first parameter
    // is the data that is to be filtered, and the second is an
    // argument that may be passed with a colon (searchFor:searchString)

    return function(arr, searchString){

      if(!searchString){
        return arr;
      }

      var result = [];

      searchString = searchString.toLowerCase();

      // Using the forEach helper method to loop through the array
      angular.forEach(arr, function(item){

        if(item.title.toLowerCase().indexOf(searchString) !== -1){
          result.push(item);
        }

      });

      return result;
    };

  });
  // Instant filter search end.*/

  </script>

</body>
</html>

spotify_list/templates/spotify_list/song_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Top Spotify Songs to MP3</title>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700|Merriweather:400italic,400,700' rel='stylesheet' type='text/css'>
  <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'spotify_list/styles.css' %}">
  <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

{% load spotify_extras %}

<body id="home">

  <div class="page-wrap">

  <div class="alert alert-success" role="alert">
    <a href="{% url 'spotify_list:dl_any_mp3' %}" class="alert-link">
      Nuevo: Extraer MP3 de cualquier vídeo.
    </a>
  </div>
    <div class="content col-md-offset-2 col-md-8">
      <h1 class="header">Top 100 canciones de <span class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            {{ country }}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="{% url 'spotify_list:index' 'spain' %}">Spain</a></li>
            <li><a href="{% url 'spotify_list:index' 'usa' %}"}}>USA</a></li>
            <li><a href="{% url 'spotify_list:index' 'uk' %}"}}>U.K.</a></li>
            <li><a href="{% url 'spotify_list:index' 'do' %}">R.D.</a></li>
            <li><a href="/spotify_list/global"}}>Mundial</a></li>
          </ul>
        </span>
      </h1>

      <div>
        <div class="bar buscador">
          <input type="text" size="40" onkeyup="InstantSearch(this)" placeholder="¿Buscas alguna canción o artista?" />
        </div>

        <div class="all-songs-container">
          {% for song in object_list %}
          <div class="song-container searchable" style="min-height: 160px; width:100%;">
            <div class="primera-fila" style="width:100%; margin-left:10%; font-weight: bold; font-size: 1.5em;">
              <b class="titulo-cancion">{{song.title}}</b>
            </div>
            <div class="segunda-fila">
              <div class="posicion" style="width:10%; float:left; font-weight: bold; font-size: 3.5em; color: #707070;">
                <b>{{song.position}}</b>
              </div>
              <div class="artista" style="width:90%; color: #707070;">
                <b class="artista-cancion">{{song.artist}}</b>
              </div>
            </div>
            <div class="tercera-fila" style="width:100%; margin-left:10%; padding-top: 10px;">
              <button type="button" class="btn btn-default btn-lg spotify" data-spotify_id="{{song.spotify_id}}">
                <span class="glyphicon glyphicon-music" aria-hidden="true"></span> - Escuchar en Spotify
              </button>


              <button type="button" class="btn btn-default btn-lg yt" data-yt_id="{{song.yt_id}}">
                <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> - Ver vídeo
              </button>

              <a href="/spotify_list/download_file/{{song.yt_id}}">
              <button type="button" class="btn btn-default btn-lg">
                <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span> - Descargar MP3
              </button>
              </a>

              <div class="embedded-spotify" id="{{song.spotify_id}}"></div>
              <div class="embedded-yt" id="{{song.yt_id}}"></div>
            </div>
          </div>
          {% endfor %}
        </div>
        <br/>
      </div>

    </div>
  </div>
  <div class="clearfix"></div>

  <div class="site-footer">
  Site by: <a target="_blank" href="http://ricardomol.com">Ricardo Molina</a>.
  </div>

  <script type="text/javascript">

  function InstantSearch (search_input) {
    search_text = search_input.value.toLowerCase();

    var exp = new RegExp(search_text, 'i');

    $('.searchable').each(function() {
      var isMatch = exp.test($('.titulo-cancion', this).text()) || exp.test($('.artista-cancion', this).text());
      $(this).toggle(isMatch);
    });
  };


  $(function(){

      $('.spotify').click(function(e){
        e.preventDefault();
        $('.embedded-yt').empty();
        $('.embedded-spotify').empty();
        var selected_spotify_id = $(this).attr("data-spotify_id");
        var selected_spotify_div = $("#" + selected_spotify_id);
        selected_spotify_div.html("<iframe src='https://embed.spotify.com/?uri=spotify:track:" + selected_spotify_id + "' width='640' height='80' frameborder='0' allowtransparency='true'></iframe>");
      });
      
      $('.yt').click(function(e){
        e.preventDefault();
        $('.embedded-yt').empty();
        $('.embedded-spotify').empty();
        var selected_yt_id = $(this).attr("data-yt_id");
        var selected_yt_div = $("#" + selected_yt_id);
        selected_yt_div.html("<iframe width='640' height='390' allowfullscreen src='http://www.youtube.com/embed/" + selected_yt_id + "?&playsinline=1&autoplay=1" + "'></iframe>");
      });

  });

  </script>

</body>
</html>

spotify_list/templates/spotify_list/update_lists.html
<html>
<head>
	<title></title>
</head>
<body>
	Lists updated.
</body>
</html>